version: "3.8"

services: 
    
    node-red:
        container_name: "MaranduhaBot"
        build: .
        restart: on-failure:3
        ports:
            - "1881:1881"
        env_file:
            - ./envs/envs.env
        volumes:
            - ./shared:/shared